### ISSUE TITLE
Ik denk dat de input data wel op de github zou moeten staan?

### ISSUE THREAD

**Issue by lschoonheid** [lschoonheid/Science-Park-Thunder-Fingers#11]
```
# ISSUE: Ik denk dat de input data wel op de github zou moeten staan?
```

https://github.com/lschoonheid/Science-Park-Thunder-Fingers/blob/73e258a21825b56661a824e951cc2e91fddb27da/.gitignore#L10

**Comment by juliajirina** [comment]
Ja, maar hoeft niet elke keer opnieuw gedownload te worden als je pullt toch? dus is het dan niet handig om t in gitignore te zetten? Of wordt ie dan ook niet gedownload als ie geforkt wordt?
